### ISSUE TITLE
Maybe spec issue: @room matches even if it is in the middle of a word

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/matrix-doc#2913] opened 2020-12-16 01:26 UTC
**Describe the bug**

Element Android implements @room matching by doing a simple contains match on the body, leading to the following issue: https://github.com/vector-im/element-android/issues/2541

At first this looks like it is obviously an element android bug, as it matches any text containing @room, like `thisis@roommatchingtext` and `@roomba`, and all other clients seem to do it differently, but reading the comments in the implementation leads me to believe otherwise: https://github.com/matrix-org/matrix-android-sdk2/blob/235d432dfc102e2af0cbe9828fdd6b61af3310e1/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/EventMatchCondition.kt#L57

It mentions the following rule in the spec: 

> Patterns with no special glob characters should be treated as having asterisks prepended and appended when testing the condition.

https://matrix.org/docs/spec/client_server/r0.6.1#conditions

This means keyword matches match at any point in body, ignoring word delimiters. While that in itself could be considered less than ideal, in the case of `@room` rules, this is especially confusing, since moderators can trigger them by accident. Currently `@room` rules are specified in the spec with the `event_match` condition on `content.body` with the text `@room`. The above rule then causes this to match using `*@room*` on the message body.

I believe we should investigate, what is the optimal behaviour for `event_match` conditions and the roomnotif rule specifically. We certainly want `@room:` to match, but should `nico@roomba.com` match? What was the reasoning that led to the current wording?

This may even not actually be a spec issue. It could be that Synapse and Element/Web implement it wrong. Alternatively I could be reading the spec wrong, but I think I did not (this time).

**Comment by Extarys** [comment] 2020-12-16 02:21
(Sorry again for spamming everyone on android with my message)
Thanks for taking the time to open this as I'm not experienced enough with the matrix backend/spec. :heart: 

[You can now mark this as off topic]

**Comment by zecakeh** [comment] 2021-03-24 10:36
This seems like a duplicate of #2637

**Comment by richvdh** [comment] 2021-03-24 10:39
yes, I think it is.

**Closed by richvdh** 2021-03-24 10:39 UTC
