### ISSUE TITLE
Feature request: self-destruct messages X time after sending

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-doc#3223] opened 2021-05-28 20:31 UTC
**Suggestion**

I would like to set an event in my room to have all messages removed from well-behaved-unpatched homeservers X time from being sent.

For example, [Telegram has options off, 24 hours or 7 days](https://telegram.org/blog/autodelete-inv2#auto-delete-messages), after it's set, messages that turn that time old are removed from the group. Similar feature exists in [Signal](https://support.signal.org/hc/en-us/articles/360007320771-Set-and-manage-disappearing-messages) and WhatsApp.

I understand that there is currently https://github.com/matrix-org/matrix-doc/pull/2228 implemented in Synapse experimentally, but it's a per-event rather than per-room.

*Keywords: self-destructing messages, disappearing messages, automatically removing messages, message auto remove, message auto deletion*

**Comment by Mikaela** [comment] 2021-06-08 09:22
It turns out that this feature exists and can be used through /devtools while it's not particularly human friendly and uses milliseconds, (thanks @sl:feneas.org) [permalink](https://matrix.to/#/!xZdLRpNKmLAfeHOAgy%3Afeneas.org/%24KrNq0G4q-dmB6ubg59oBPolAc-y84mMt4387bdDP7cI)

* https://brendan.abolivier.bzh/matrix-retention-policies/

**Comment by richvdh** [comment] 2021-06-21 11:00
I think this is a basically a duplicate of #440. 

The retention policies implemented in Synapse follow a spec proposal at #1763, and as you note go a long way to solving this.

**Closed by richvdh** 2021-06-21 11:00 UTC
Labels: improvement
