### ISSUE TITLE
Message power levels

### ISSUE THREAD

**Issue by Biep** [matrix-org/matrix-doc#2672] opened 2020-07-07 15:48 UTC
Ideally messages would have a power level too, showing who can read it. Setting the power level above zero means communicating with the admins only - and admins themselves (including abuse bots) can set power levels higher to remove material from public view.
Some possible use cases:
- Inter-admin discussions (including or excluding mods and whatever other levels there might be);
- Removing abusive messages without destroying the trail - so auditing remains possible.
- Sending "private" messages to all admins at once - better than having to choose one single admin to DM;
- Having "advanced" material only readable for members who have reached that state (reflected in a slightly raised power level).

**Comment by tulir** [comment] 2020-07-07 16:02
This doesn't seem realistically possible, especially changing the "power level" after sending. The only secure way to implement it without significantly changing federation would be to encrypt the messages, but that could be problematic in big rooms, and obviously won't let you hide messages after they're sent.

> Removing abusive messages without destroying the trail - so auditing remains possible.

This should probably be solved by adding a way for room admins to get redacted event content from the server.

**Comment by turt2live** [comment] 2020-07-07 16:28
Duplicate of https://github.com/matrix-org/matrix-doc/issues/482

**Closed by turt2live** 2020-07-07 16:28 UTC

**Comment by Biep** [comment] 2020-07-28 21:19
This is actually one aspect of a much more comprehensive [earlier proposal](https://github.com/vector-im/riot-web/issues/11600).
