### ISSUE TITLE
Link to spec-core-team is 404 if you aren't in the matrix-org organization

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix-doc#1749] opened 2018-12-12 03:56 UTC
The link to "Meet the members of the Core Team" on https://matrix.org/docs/spec/proposals is 404 if you aren't in the organization so it isn't that helpful.

Is there a way to make the team public or should a separate page be set up that lists the members of the core team?

Introduced here: https://github.com/matrix-org/matrix-doc/commit/8121bef771c97c83953148afd2e9ac431d9e2580#diff-587ffef8f8d50dd2caa2a1c06a5697b1R19

**Comment by turt2live** [comment] 2018-12-12 04:03
Duplicate of https://github.com/matrix-org/matrix.org/issues/283

**Closed by turt2live** 2018-12-12 04:03 UTC
