### ISSUE TITLE
`redacts` event-level key not specified for Room Events

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2684] opened 2020-07-11 12:38 UTC
The [redaction API](https://matrix.org/docs/spec/client_server/r0.6.1#id40) specifies an additional __event-level__ `redacts` key for indicating which event is being redacted, but this key is not listed in the [Room Event field specification](https://matrix.org/docs/spec/client_server/r0.6.1#room-event-fields) (not as "Optional" either), despite existing outside of the `content` object.

Not sure if this is specific to the `redacts` key, or whether there are other event-level extensions that are not listed in the Room Event format.

Related: #502

**Comment by turt2live** [comment] 2020-07-11 16:46
This is effectively a duplicate of https://github.com/matrix-org/matrix-doc/issues/502

**Closed by turt2live** 2020-07-11 16:46 UTC
