### ISSUE TITLE
Override notifications per-client

### ISSUE THREAD

**Issue by madduck** [matrix-org/matrix-doc#2447] opened 2020-02-27 03:49 UTC
It's my understanding that notification preferences are currently stored per-account, i.e. "all messages in this room", "mentions-only in this other room"…

I have two workstations, at home and at the office, but my life isn't clearly separated like that. I also have a mobile client. There are channels I want to get notified about for everything at the office, but not at home, and mobile only if there are mentions, etc..

Would it be possible to extend the spec to allow per-device overrides of the account/room defaults?

**Comment by turt2live** [comment] 2020-02-27 06:15
Duplicate of https://github.com/matrix-org/matrix-doc/issues/1164

**Closed by turt2live** 2020-02-27 06:15 UTC

**Comment by madduck** [comment] 2020-02-27 10:56
> Duplicate of #1164

I don't quite understand, nor do I see a resolution in #1164 that helps me understand.

**Comment by turt2live** [comment] 2020-02-27 15:22
Notifications are push rules, and clients are devices.
