### ISSUE TITLE
Broken links to "Receiving notifications"

### ISSUE THREAD

**Issue by babolivier** [matrix-org/matrix-doc#2656] opened 2020-06-24 11:15 UTC
Both the `/sync` response spec and the "Receipt" section link to https://matrix.org/docs/spec/client_server/latest#receiving-notifications as the "Receiving notifications" section, but its actual URL is https://matrix.org/docs/spec/client_server/latest#id91 (or `#id81` on `/unstable`).

**Comment by Half-Shot** [comment] 2020-06-24 11:20
Dupe of #2623

**Closed** 2020-06-24 11:20 UTC
