### ISSUE TITLE
Replace reCAPTCHA with a libre alternative

### ISSUE THREAD

**Issue by Kreyren** [matrix-org/matrix-doc#3220] opened 2021-05-27 18:35 UTC
This has been discussed on FSF's community meetup in 27/05/2021 specified as a blocker for an adoption of the protocol.

**Comment by turt2live** [comment] 2021-05-27 18:45
Duplicate of https://github.com/matrix-org/matrix-doc/issues/1281

**Closed by turt2live** 2021-05-27 18:45 UTC
