### ISSUE TITLE
Blue hyperlink on blueish background is hard to read in spec CSS

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#2495] opened 2020-04-11 20:07 UTC
And the CSS in general needs love.

**Comment by richvdh** [comment] 2020-04-11 20:36
related: https://github.com/matrix-org/matrix.org/issues/35

**Comment by turt2live** [comment] 2020-04-13 06:49
Duplicate of https://github.com/matrix-org/matrix-doc/issues/2119

**Closed by turt2live** 2020-04-13 06:49 UTC
