### ISSUE TITLE
The algorithm for picking auth_events is incomplete

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/matrix-doc#1495] opened 2018-08-08 12:31 UTC
The full algorithm in synapse is:

https://github.com/matrix-org/synapse/blob/33b60c01b5e60dc38b02b6f0fd018be2d2d07cf7/synapse/api/auth.py#L555-L619

**Comment by turt2live** [comment] 2018-08-08 13:40
Duplicate of https://github.com/matrix-org/matrix-doc/issues/1430

**Closed by turt2live** 2018-08-08 13:40 UTC
Labels: spec-bug
