### ISSUE TITLE
Standardisation of server administration API

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/matrix-doc#3193] opened 2021-05-14 07:49 UTC
Currently, each server implements its own administration APIs. This means each server administrator needs to learn implementation specific commands and procedures. If a standardised server administration API existed, then the server administrators could just log in using any client and manage their server using the client's native user interface. Even though some settings will still be implementation specific, a discovery service could present those endpoints in a standardised manner, so the client could present them in a native looking manner too.

**Comment by erkinalp** [comment] 2021-05-14 07:49
One of the first steps towards standardisation of server administration is Limits API (#3018).

**Comment by t3chguy** [comment] 2021-05-14 09:35
Duplicate of https://github.com/matrix-org/matrix-doc/issues/1411

**Closed by t3chguy** 2021-05-14 09:35 UTC
Labels: improvement
