### ISSUE TITLE
SUGGESTION: Slowmode

### ISSUE THREAD

**Issue by TheEvilSkeleton** [matrix-org/matrix-doc#2565] opened 2020-05-22 15:16 UTC
Hello, I have no idea where to add this so I will add it here. Discord has a "[Slowmode](https://www.techjunkie.com/discord-slow-mode/)" feature that is really useful in servers. People would appreciate it if you add it.

**Comment by turt2live** [comment] 2020-05-22 15:29
Duplicate of https://github.com/matrix-org/matrix-doc/issues/1949

**Closed by turt2live** 2020-05-22 15:29 UTC
