### ISSUE TITLE
User disambiguated display names should be disambiguated according to Unicode normal form

### ISSUE THREAD

**Issue by Ralith** [matrix-org/matrix-doc#350] opened 2016-07-11 01:30 UTC
This would prevent abuses where a user crafts a display name using distinct code points that display as visually identical glyphs compared to another user by reducing display names to a normal form before comparing them for the purposes of disambiguation.

Four [Unicode normal forms](http://www.unicode.org/reports/tr15/) are defined, and I believe two of them are relevant here. NFC describes a form of a Unicode string which will have the same appearance, while NFKC describes a form which has had broad classes of similar-but-not-identical glyphs and sequences thereof (such as ligatures versus discrete glpyhs and sub/superscripts versus numerals) replaced with canonical forms which may not have precisely the same appearance. 

Using NFC should ensure that, for a sufficiently attentive user and high-quality rendering, all non-disambiguated display names are visually distinct. Using NFKC should additionally ensure that many visually distinct names which might be nonetheless be commonly mistaken for each other are disambiguated. Before opening a pull request to change the wording of the specification, I'd like input on which approach people see as more suitable.

**Comment by richvdh** [comment] 2016-07-12 11:11
Yes it should. This is something of a duplicate of https://matrix.org/jira/browse/SPEC-392.

**Closed by richvdh** 2016-07-12 11:11 UTC
