### ISSUE TITLE
c2s spec has separate 'events' and 'event structure' sections, which is confusing

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#1994] opened 2019-05-08 13:20 UTC
[events](https://matrix.org/docs/spec/client_server/r0.4.0.html#events); [event structure](https://matrix.org/docs/spec/client_server/r0.4.0.html#event-structure). It seems like these two should be merged

**Comment by turt2live** [comment] 2019-05-08 15:00
Related: https://github.com/matrix-org/matrix-doc/issues/1527

**Comment by turt2live** [comment] 2019-06-06 04:34
actually going to consider this a duplicate of https://github.com/matrix-org/matrix-doc/issues/1527

**Closed by turt2live** 2019-06-06 04:34 UTC
Labels: clarification, client-server
