### ISSUE TITLE
Registration fallback doesn't seem to be specced

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#2411] opened 2020-01-15 10:14 UTC
but https://matrix.org/_matrix/static/client/register is a thing

**Comment by richvdh** [comment] 2020-01-15 10:15
dunno if it works though, tbh

**Comment by richvdh** [comment] 2020-01-15 10:29
(it doesn't: https://github.com/matrix-org/synapse/issues/6709)

**Comment by turt2live** [comment] 2020-01-15 16:50
is this not https://matrix.org/docs/spec/client_server/r0.6.0#fallback ? (because register is UIA)

**Comment by richvdh** [comment] 2020-01-15 17:58
well, not really: https://matrix.org/docs/spec/client_server/r0.6.0#fallback specifies fallbacks for individual UIA steps, but still expects the client to do the mechanics of UIA itself. 
https://matrix.org/_matrix/static/client/register is supposed to take care of the entire UIA registration flow from start to finish.

However, given it seems to have been broken ever since we removed the non-UIA registration endpoints, and it has never been specced, maybe we should just say that clients have to implement UIA if they want to support registration.

**Comment by richvdh** [comment] 2020-06-11 14:53
ok, this has been broken forever and nobody seems to care that much, so rather than fixing it and speccing it, I think we should remove it.

**Comment by turt2live** [comment] 2020-06-11 15:26
@richvdh lack of activity on an issue isn't an indicator of it being useless. By existing in synapse it is considered to exist, for better or worse, which is what issues under `spec-omission` track: spec that's literally just missing but otherwise considered truthful.

**Comment by KitsuneRal** [comment] 2020-06-14 15:46
> However, given it seems to have been broken ever since we removed the non-UIA registration endpoints, and it has never been specced, maybe we should just say that clients have to implement UIA if they want to support registration.

Which is a pretty high bar, given how versatile UIA is. To have an end-to-end UIA fallback would be really nice - especially if it were aligned with SSO flow, ending with HTTP, rather than JavaScript, callback.

**Comment by bmarty** [comment] 2022-02-22 15:51
I can confirm that it was working, but today it does not work anymore. At least Element Android still relies on it if a registration stage is unknown and can't be handled natively

**Comment by richvdh** [comment] 2022-02-22 17:31
@bmarty I think you are confusing UIA stage fallback (`https://matrix.org/_matrix/client/v3/auth/.../fallback/...`) which is [specced](https://spec.matrix.org/v1.2/client-server-api/#fallback) with *registration* fallback (`https://matrix.org/_matrix/static/client/register`), which is not, and is broken.

**Comment by richvdh** [comment] 2022-02-22 17:50
> By existing in synapse it is considered to exist, for better or worse,

The thing is, it doesn't exist in Synapse. All that exists in Synapse is a thing that serves you error messages.

If we suddenly decided it was a useful thing that we wanted to re-introduce, I'd expect us to go through an MSC process.

I really don't buy the idea that we should spec a thing that hasn't existed for over three years.

**Comment by richvdh** [comment] 2022-02-22 17:52
> To have an end-to-end UIA fallback would be really nice

I don't disagree with this, but still - I'd expect it to go through MSC, and in any case the OAuth2 changes are looking more promising IMHO.

**Comment by turt2live** [comment] 2022-02-22 17:55
yea, 2 years ago the MSC process didn't feel correct for this sort of thing, but now it does. Re-closing.

**Closed by turt2live** 2022-02-22 17:55 UTC
Labels: spec-omission
