### ISSUE TITLE
Request: Ability to hint at pronouns in user profile for clients to use

### ISSUE THREAD

**Issue by jfrederickson** [matrix-org/matrix-doc#2478] opened 2020-03-28 13:26 UTC
Currently, most Matrix clients seem to default to gender-neutral pronouns for messages like:

> user1 changed their display name

This is probably the safest option without having more information, but allowing a user to signal their desired pronouns would offer more flexibility. Some people prefer pronouns that differ from what many people would assume based on their name and photo, and allowing clients to reinforce this information could help.

**Comment by Half-Shot** [comment] 2020-03-28 13:28
This would likely sit well inside extensible profiles, which is https://github.com/matrix-org/matrix-doc/pull/1769

**Comment by turt2live** [comment] 2020-03-28 19:51
Duplicate of https://github.com/matrix-org/matrix-doc/issues/489

**Closed by turt2live** 2020-03-28 19:51 UTC
