### ISSUE TITLE
/rooms/.../members is missing `at` and `not_membership` parameters

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-doc#1945] opened 2019-03-27 16:27 UTC
Riot is calling these, but they are not given in the spec under https://matrix.org/docs/spec/client_server/unstable.html#get-matrix-client-r0-rooms-roomid-members.

This could be a synapse or a Riot bug, but given it sounds like it's useful, I'm tracking it in here.

**Comment by turt2live** [comment] 2019-03-27 18:06
Duplicate of https://github.com/matrix-org/matrix-doc/issues/1227

**Comment by Half-Shot** [comment] 2019-03-28 10:25
No it's not. That proposal happened and the resulting spec PR got merged, with this missing https://github.com/matrix-org/matrix-doc/pull/1758

**Comment by turt2live** [comment] 2019-03-28 10:48
The spec pr is not fully merged, and I don't think it's a good idea to keep tracking lazy loading omissions like this. I'd rather see someone go through and properly make the spec reflect reality for lazy loading so we can consider the proposal merged.

**Comment by Half-Shot** [comment] 2019-03-28 10:53
With respect, this is one of those things that is going to get lost. I would be fine with this, if lazy-loading wasn't now in use by Riot by default and therefore any third party implementations now HAVE to implement these keys to have a working client.

It's a bit lame to have open issues, but really I don't know why we have a situation why a spec isn't fully merged. With respect to fixing the spec, I am happy to close this once we have fixed the issue.

**Comment by Half-Shot** [comment] 2019-03-28 11:01
Discussed oob with @turt2live that we can keep the issue open, but there are people on the case.

**Comment by richvdh** [comment] 2019-05-10 10:18
see also #1868

**Closed** 2019-06-11 15:39 UTC
Labels: client-server, spec-omission
