### ISSUE TITLE
m.login.email.identity example has threepidCreds defined as an array, not an object

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#3156] opened 2021-04-29 17:50 UTC

**Comment by turt2live** [comment] 2021-04-29 17:52
also msisidn

**Comment by deepbluev7** [comment] 2021-11-03 16:04
It is also spelled threepidCreds in the spec and synapse answers to that with the helpful error: `Missing threepid_creds`

**Comment by turt2live** [comment] 2021-11-03 16:07
See https://github.com/matrix-org/matrix-doc/issues/2220

**Comment by richvdh** [comment] 2021-11-04 11:55
this appears to be a direct duplicate of #2189

**Closed by richvdh** 2021-11-04 11:55 UTC
Labels: spec-bug, client-server
