### ISSUE TITLE
Add DELETE for avatar_url or add documentation on erasing the avatar url

### ISSUE THREAD

**Issue by werner291** [matrix-org/matrix-doc#2333] opened 2019-10-29 14:31 UTC
In the current spec (https://matrix.org/docs/spec/client_server/r0.5.0#profiles), a user profile not having an avatar_url appears to be a valid state, while there does not appear to be any documented way in which one can return a user account to this state after an avatar has been posted.

Therefore, I propose one of the following to be done:
- Add a DELETE option to the  /_matrix/client/r0/profile/{userId}/avatar_url path.
- Document an alternative way of removing the avatar url (such as PUTing a null or empty url).
- Explicitly disallow erasing the avatar_url and documenting the reason for this choice.

**Comment by turt2live** [comment] 2019-10-29 14:49
Duplicate of https://github.com/matrix-org/matrix-doc/issues/1674

**Closed by turt2live** 2019-10-29 14:49 UTC
