### ISSUE TITLE
threepidCreds should be called threepid_creds

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/matrix-doc#2207] opened 2019-07-31 16:09 UTC
There is a discrepancy between synapse and the spec in trying to auth using email from id server. 

This issue was cribbed heavily from https://github.com/matrix-org/synapse/issues/5748
"According to docs, the auth looks like this:

https://github.com/matrix-org/matrix-doc/blob/ad5d46d3317bd3d016ed7bf1e3fb5ce1f8d7fef1/specification/client_server_api.rst#L797

But according to synapse, it should be named this:

https://github.com/matrix-org/synapse/blob/54283f3ed49ce40059e9f0746f2ded08ce3a5b9e/synapse/handlers/auth.py#L454

So the two differences are the key name and whether it should contain an object or array."

Given that this is out in the wild and that the spec tends to snake_case I propose that this should be fixed in the spec rather than implementation even though technically this is a bug in Synapse.

**Comment by turt2live** [comment] 2019-07-31 16:25
Duplicate of https://github.com/matrix-org/matrix-doc/issues/2189

**Closed by turt2live** 2019-07-31 16:25 UTC
Labels: spec-bug
