### ISSUE TITLE
IS spec's /unbind endpoint is missing info on authentication

### ISSUE THREAD

**Issue by babolivier** [matrix-org/matrix-doc#2166] opened 2019-07-10 14:28 UTC
The spec for this endpoint [says](https://matrix.org/docs/spec/identity_service/r0.2.1#post-matrix-identity-api-v1-3pid-unbind):

> The identity server should authenticate the request in one of two ways:
> 
> 1. The request is signed by the homeserver which controls the `user_id`.
> 2. The request includes the `sid` and `client_secret` parameters, as per `/3pid/bind`, which proves ownership of the 3PID.

However, it is missing documentation on how to authenticate in the first case.

IMHO the logical way to do it would be through a `signatures` property in the request's body, as it's done elsewhere in this spec, but this property is missing here.

On the other hand, both Synapse and Sydent implement this auth through a federation header (described [here](https://matrix.org/docs/spec/server_server/unstable#request-authentication)), c.f. https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/identity.py#L199, which sounds wrong to me.

**Comment by turt2live** [comment] 2019-07-10 14:29
Duplicate of https://github.com/matrix-org/matrix-doc/issues/2163

**Closed by turt2live** 2019-07-10 14:29 UTC

**Comment by babolivier** [comment] 2019-07-10 14:35
Gah, sorry, I missed that issue
