### ISSUE TITLE
Are User-Interactive Authentication flows ordered?

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#1986] opened 2019-05-03 17:04 UTC
The [specification](https://matrix.org/docs/spec/client_server/r0.4.0.html#user-interactive-api-in-the-rest-api) states:

> The client then chooses a flow and attempts to complete one of the stages. It does this by resubmitting the same request with the addition of an auth key in the object that it submits. This dictionary contains a type key whose value is the name of the authentication type that the client is attempting to complete.

What is unclear here, is whether the client is free to complete the stages in *any* order, or whether it is required to follow the exact order specified by the homeserver.

For example, in:

```json
{
  "flows": [
    {
      "stages": [ "example.type.foo", "example.type.bar" ]
    },
    {
      "stages": [ "example.type.foo", "example.type.baz" ]
    }
  ],
  "params": {
      "example.type.baz": {
          "example_key": "foobar"
      }
  },
  "session": "xxxxxx"
}
```

... which of the following two is correct?

1. The client *must* first complete the `example.type.foo` stage, and after completion is allowed to complete either `example.type.bar` or `example.type.baz`.
2. The client is free to complete *any* of the three stages, and after that complete whichever remaining stage is necessary to complete an entire flow.

**Comment by turt2live** [comment] 2019-05-30 00:28
Fixed by https://github.com/matrix-org/matrix-doc/pull/2042
(Duplicate of https://github.com/matrix-org/matrix-doc/issues/1134)

**Closed by turt2live** 2019-05-30 00:28 UTC
Labels: clarification, client-server
