### ISSUE TITLE
Figure out the answer to the threepidCreds vs threepid_creds debate

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#3157] opened 2021-04-29 17:54 UTC
There are several arguments as to whether it is a spec issue or a synapse issue. Needs discussion.

https://github.com/vector-im/element-web/issues/10312
https://github.com/matrix-org/matrix-react-sdk/pull/3211
https://github.com/matrix-org/synapse/issues/5665
https://github.com/matrix-org/matrix-doc/issues/2220

**Comment by aaronraimist** [comment] 2021-04-29 18:19
Duplicate of #2220 and #2189

**Closed** 2021-04-29 18:56 UTC
