### ISSUE TITLE
old versions of the spec should have a header which warns and links to latest version

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#1575] opened 2018-08-27 12:32 UTC
as fun as it is to accidentally end up reading r0.0.1 of the CS API by accident

**Comment by turt2live** [comment] 2018-08-27 14:39
Related: https://github.com/matrix-org/matrix-doc/issues/1499

**Comment by turt2live** [comment] 2018-09-06 22:40
Duplicate of https://github.com/matrix-org/matrix-doc/issues/845

**Closed by turt2live** 2018-09-06 22:40 UTC
Labels: aesthetic, improvement
