### ISSUE TITLE
/_matrix/client/r0/joined_groups

### ISSUE THREAD

**Issue by TobiasNickel** [matrix-org/matrix-doc#2573] opened 2020-05-25 15:23 UTC
Hi, could not find any documentation for the joined groups API, should it be part of this Matrix-doc?

```
GET /_matrix/client/r0/joined_groups
{"groups": group_ids}
```

I was doing some tests with the Matrix protocol, using the Riot web client. I have let it connect to my personal localhost server made with nodejs. I wanted to play and explore the API this way. The webclient has already been able to login, but now I found the client is doing the request above.

Searching in the synapse repo, I found there is the implementation for that API: https://github.com/matrix-org/synapse/blob/b2b86990705de8a099093ec141ad83e09f182034/synapse/handlers/groups_local.py

But for now I can't see what the type of _group_ids_ is. 

The API was also listed here: https://github.com/matrix-org/synapse/blob/b2b86990705de8a099093ec141ad83e09f182034/docs/workers.md#synapseappclient_reader

would be awesome to find it in this swagger definition: https://matrix.org/docs/api/client-server/#/
but I could not find the source of it.

**Comment by turt2live** [comment] 2020-05-25 15:35
Duplicate of https://github.com/matrix-org/matrix-doc/issues/971 and associated issues.

**Closed by turt2live** 2020-05-25 15:35 UTC
