### ISSUE TITLE
v1.2 changelog does not merge entries with identical text

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-doc#3742] opened 2022-02-23 10:58 UTC
**Link to problem area**:

https://spec.matrix.org/v1.2/changelog/#client-server-api

**Issue**

![image](https://user-images.githubusercontent.com/1012976/155242134-8bb81d29-3c80-47f2-9efb-9d2f02e18032.png)

**Comment by turt2live** [comment] 2022-02-23 15:29
Duplicate of https://github.com/matrix-org/matrix-doc/issues/3441

Only affects rendered changelog when using the fragments. After generation (like v1.2 in unstable), it's working off of the towncrier output

**Closed by turt2live** 2022-02-23 15:29 UTC
Labels: aesthetic
