### ISSUE TITLE
Request: allow room display name /myroomnick and room avatars override global display name and avatar

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-doc#2691] opened 2020-07-21 08:19 UTC
I was told that this is the most appropiate repository for this.

I generally wish to be known by my global displayname, but there are a few rooms where I would like to have a different name and then there are a few dozen rooms where I would like to be known by my full name as they are somewhat professional. Currently when I change my display name in Element by `/nick`, the rooms that I have a separate name in get overwritten and then I have to start going through them by `/myroomnick` again.

This also affects room specific avatars.

**Comment by Sorunome** [comment] 2020-07-21 08:28
AFAIK synapse changing m.room.member event in all rooms you are in when changing profile is actually behaviour not mentioned in the spec - the spec doesn't say what servers should do if you change your profile information

So, while there is a need to clarify that, it is also a good idea to make local room changes "sticky".

**Comment by uhoreg** [comment] 2020-07-21 14:24
Duplicate of https://github.com/matrix-org/matrix-doc/issues/545

**Closed by uhoreg** 2020-07-21 14:24 UTC

**Comment by tulir** [comment] 2020-12-05 19:49
This is a duplicate of #1376, not #545
