### ISSUE TITLE
/messages does not provide a way of saying that you cannot paginate further

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#2251] opened 2019-08-28 11:23 UTC
We need to define the error code or mechanism to inform the user that they can't back-paginate further via /messages because the server has run out of DAG.

**Comment by ara4n** [comment] 2019-08-28 11:37
see https://github.com/matrix-org/synapse/issues/1623 and https://github.com/vector-im/riot-web/issues/2566

**Comment by KitsuneRal** [comment] 2019-08-29 04:43
Do we really need to invent anything here if `/messages` returns state changes and `m.room.create` is still the very first event no matter how you purge messages?

**Comment by richvdh** [comment] 2019-08-29 09:30
it's not really a spec-bug imho: it's something we need to agree on and spec.

@KitsuneRal: that is one solution, but there are others which would make just as much (or more) sense. It's worth remembering that /messages lets you go both ways so we could do with a solution that works in the other direction too.

**Comment by turt2live** [comment] 2019-08-29 18:23
err, yes - it should be an improvement not a bug. I wonder which issue I was trying to label as a bug....

**Comment by ara4n** [comment] 2019-09-03 13:31
According to https://github.com/matrix-org/matrix-doc/pull/1763#discussion_r318864900 @turt2live thinks that the absence of a `next_batch` token should be specced to mean "you cannot paginate further", which feels very sane to me.  Shall we do that (if it's not already?)

**Comment by richvdh** [comment] 2019-09-03 13:51
`/messages` doesn't have a `next_batch`. I think you mean `end`, in which case +1

**Comment by joepie91** [comment] 2020-07-21 18:17
> Do we really need to invent anything here if `/messages` returns state changes and `m.room.create` is (supposed to be) still the very first event no matter how you purge messages?

Yes. The same problem occurs when you specify a `to` parameter (to fetch missing backlog in a limited `/sync` response for example), in which case you don't know what the final event is going to be. The only solutions right now are:
1. Checking whether the amount of results is less than the limit (fragile, will break in 1/Nth of cases)
2. Continuing to paginate until an empty chunk is produced (seemingly reliable, but requires a pointless extra request)

**Comment by richvdh** [comment] 2021-03-17 18:54
> Continuing to paginate until an empty chunk is produced (seemingly reliable, but requires a pointless extra request)

not entirely reliable, sadly. Synapse will sometimes return empty chunks if there is a section of timeline you're not allowed to see (eg because you weren't in the room).

**Comment by richvdh** [comment] 2021-04-30 11:39
For the record, it looks like matrix-js-sdk currently decides that it's at the end of the timeline if `start == end` in the response.

**Comment by richvdh** [comment] 2021-09-20 17:53
This got fixed by #3353.

**Closed by richvdh** 2021-09-20 17:53 UTC
Labels: improvement, client-server

**Comment by bakkot** [comment] 2021-10-02 21:15
To be clear, accepted solution is "you can detected the end of the line by the absence of an `end` token in the response", right?

I note that this is _not_ the behavior on `matrix.org` currently, which will always return an `end` token. That's fine, but it's a bit annoying that someone just reading the spec [e.g. me] is going to end up in an infinite loop when trying to write a client against the `matrix.org` homeserver.

**Comment by richvdh** [comment] 2021-10-04 10:43
> I note that this is not the behavior on matrix.org currently, which will always return an end token.

please file an issue against https://github.com/matrix-org/synapse
