### ISSUE TITLE
Example for encrypted attachments shows unspecced and redundant 'mimetype' property

### ISSUE THREAD

**Issue by joepie91** [matrix-org/matrix-doc#2699] opened 2020-07-26 10:13 UTC
In [the spec](https://matrix.org/docs/spec/client_server/r0.6.1#encrypted-files), the following example is shown (I snipped out irrelevant bits):

```js
{
  "content": {
    // ...
    "file": {
      // ...
      "mimetype": "image/jpeg",
      // ...
    },
    "info": {
      "mimetype": "image/jpeg",
      // ...
      "thumbnail_file": {
        // ...
        "mimetype": "image/jpeg",
        // ...
      },
      "thumbnail_info": {
        // ...
        "mimetype": "image/jpeg",
        // ...
      },
      // ...
    },
    "msgtype": "m.image"
  },
  // snip
}
```

In the `file` and `thumbnail_file`, the `mimetype` is duplicated from the file and thumbnail metadata respectively, but the spec makes no mention of these duplicated fields in its property lists for these objects. It also does not specify how conflicts between these fields should be handled, which suggests they are not supposed to be there to begin with.

(Relatedly, does the example originate from Synapse output? Since that would warrant a spec compliance bug on Synapse as well.)

**Comment by uhoreg** [comment] 2020-07-26 14:55
Duplicate of https://github.com/matrix-org/matrix-doc/issues/2374

(Since this is in the encrypted part of the event, this has nothing to do with Synapse.)

**Closed by uhoreg** 2020-07-26 14:55 UTC
