### ISSUE TITLE
Room Directory needs an API to return the avatar, name, topic of a given room alias

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-doc#929] opened 2017-05-29 23:14 UTC
When someone mentions a room that you haven't joined, surely we should be able to decorate it with a proper avatar, name, etc.  This would also be useful for populating up the links in custom room directory welcome pages.

**Comment by turt2live** [comment] 2018-03-05 16:46
Duplicate of https://github.com/matrix-org/matrix-doc/issues/711

**Closed** 2018-03-05 18:35 UTC
Labels: improvement
