### ISSUE TITLE
We need to either fix the "invite a new user" experience or get rid of it.

### ISSUE THREAD

**Issue by Yoric** [matrix-org/matrix-doc#2993] opened 2021-02-02 19:03 UTC
I've done some involuntary hallway testing with friends & family, trying to get them on Matrix (specifically on `matrix.org`). Some of them are technologically proficient, others newbies.

This included:

- the "share this room" link;
- the "invite-by-email" feature;
- both the web client and the Android client.

From 6 people, only two managed to get invites to work, and these are not the proficient users. The others left convinced that Element is broken, "can't replace WhatsApp", etc.

We really need to fix this experience.

**Comment by richvdh** [comment] 2021-02-03 12:39
I think it might be more of a UX issue (hence normally filed under element-web in the first instance, even though it spans multiple clients) than a spec issue, to be honest. It's not obvious from the report what would be changed at the spec (or server) level.

**Comment by turt2live** [comment] 2021-02-03 13:01
I feel this is largely a duplicate of https://github.com/matrix-org/matrix-doc/issues/2971

**Closed by turt2live** 2021-02-03 13:01 UTC
