### ISSUE TITLE
Standard for Server-to-server bridges

### ISSUE THREAD

**Issue by homebeach** [matrix-org/matrix-doc#1348] opened 2018-06-28 17:18 UTC
There should be some standard way to search for bridges in Matrix. When you create a room in Matrix you could have options like "Connect this room to IRC". If you click this option, your Matrix client will look for Matrix-IRC server from Matrix. If found the server will create corresponding room to IRC and join the Matrix users in the room to IRC. The room administrators could choose the name for room in IRC. By default the name could be same as in Matrix but the room with the same name might exist in IRC already. Users could have some suffixes like _matrix_user in case that a user with same name already exists in IRC.

**Comment by turt2live** [comment] 2018-06-28 17:23
This sounds like https://github.com/matrix-org/matrix-doc/issues/427

**Comment by homebeach** [comment] 2018-07-12 07:46
Ok there seems to exist IRC Integration that already works as "Connect to IRC" button. Would there be need to define some standard way to have such integrations for other networks?

**Comment by turt2live** [comment] 2018-09-06 22:18
I think this is a duplicate of #427 in terms of discovering other bridges in the federation. A "connect to IRC" button would be the role of a client, not necessarily the spec.

**Closed by turt2live** 2018-09-06 22:18 UTC
Labels: feature
